SCREEN_HEIGHT = 720
SCREEN_WIDTH = 1280
MENU_TITLE = "title"
MENU_MAIN = "main"
MENU_TEAM = "team"
MENU_SHOP = "shop"
MENU_SHOP_INVENTORY = "shop inventory"
MENU_PLAYER_INVENTORY = "player inventory"
MENU_PLAYER_SELL_INVENTORY = "sell inventory"
POPUP = "popup"
GAME =  "game"
QUIT = "quit"
